# Run License Finder

name: license_finder

on:
  #pull_request:
  #  types: [ opened, reopened ]
  #push:
  #  # Trigger on any branch push
  #  branches:
  #    - '**'  # Match any branch
  workflow_dispatch:
    branches:
      - '**'  # Match any branch
  workflow_call:

# Setting environment variables which can be used in the entire workflow (only in the current one)

jobs:
  license_finder:
    runs-on: 'ubuntu-latest'
    container:
      image: registry.gitlab.com/crosslend/docker/license-finder/main
      credentials:
         username: ${{ vars.LICENSE_FINDER_GITLAB_REGISTRY_USERNAME }}
         password: ${{ secrets.LICENSE_FINDER_GITLAB_REGISTRY_PASSWORD }}
    steps:
        # Checking out the GitHub license-finder repository on the runner
      - name: Checkout
        uses: 'actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608'
        with:
          path: license-finder
          repository: m0-foundation/license-finder

        # Checking out the GitHub repository on the runner
      - name: Checkout
        uses: 'actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608'
        with:
          path: ${{ github.event.repository.name }}

      - name: Check license_finder version
        run: |
          ls -la /usr/share/rvm/gems/ruby-3.2.3/bin
          #source /usr/share/rvm/scripts/rvm
          #license_finder --version

