# Run License Finder

name: license_finder

on:
  #pull_request:
  #  types: [ opened, reopened ]
  #push:
  #  # Trigger on any branch push
  #  branches:
  #    - '**'  # Match any branch
  workflow_dispatch:
    branches:
      - '**'  # Match any branch
  workflow_call:

# Setting environment variables which can be used in the entire workflow (only in the current one)

jobs:
  license_finder:
    runs-on: 'ubuntu-latest'
    container:
      image: registry.gitlab.com/crosslend/docker/license-finder/main
      credentials:
         username: ${{ vars.LICENSE_FINDER_GITLAB_REGISTRY_USERNAME }}
         password: ${{ secrets.LICENSE_FINDER_GITLAB_REGISTRY_PASSWORD }}
    steps:
        # Checking out the GitHub license-finder repository on the runner
      - name: Checkout
        uses: 'actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608'
        with:
          path: license-finder
          repository: m0-foundation/license-finder

        # Checking out the GitHub repository on the runner
      - name: Checkout
        uses: 'actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608'
        with:
          path: ${{ github.event.repository.name }}

      - name: Run license_finder
        shell: bash
        continue-on-error: true
        run: |
          # Copy dependency_decisions.yml file into /tmp folder
          cp license-finder/doc/dependency_decisions.yml /tmp/.
          cd ${{ github.event.repository.name }}

          # Check if the project_specific_dependency_decisions.yml file exists before running license_finder
          if [ -f .license-finder/project_specific_dependency_decisions.yml ]; then
            echo "Running license_finder with project-specific dependency_decisions file"
            source /usr/share/rvm/scripts/rvm; license_finder inherited_decisions add ./.license-finder/project_specific_dependency_decisions.yml; license_finder --prepare --composer-check-require-only=true --decisions-file=~/tmp/dependency_decisions.yml --python-version=3
          else
            echo "Running license_finder without project-specific dependency_decisions file"
            source /usr/share/rvm/scripts/rvm; license_finder --prepare --composer-check-require-only=true --decisions-file=~/tmp/dependency_decisions.yml --python-version=3
          fi
