# Run License Finder

name: test_license_finder

on:
  #pull_request:
  #  types: [ opened, reopened ]
  #push:
  #  # Trigger on any branch push
  #  branches:
  #    - '**'  # Match any branch
  workflow_dispatch:
    branches:
      - '**'  # Match any branch
  workflow_call:

# Setting environment variables which can be used in the entire workflow (only in the current one)
#env:
#  # Used for build_docker job
#  CONTAINER_REGISTRY: registry.gitlab.com

jobs:
  license_finder:
    runs-on: 'ubuntu-latest'
    container:
      env:
        CONTAINER_REGISTRY: registry.gitlab.com
      image: registry.gitlab.com/crosslend/docker/license-finder/main
      credentials:
         username: ${{ vars.LICENSE_FINDER_GITLAB_REGISTRY_USERNAME }}
         password: ${{ secrets.LICENSE_FINDER_GITLAB_REGISTRY_PASSWORD }}
    steps:
      - name: Check license_finder version
        run: source /usr/share/rvm/scripts/rvm; license_finder --version

